[package]
name = "boss_coin_selection"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_decimal = { version = "1.39", features = ["serde-with-float"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
